sudo: required

language: perl

services:
  - docker

before_install:
   - source <(curl https://raw.githubusercontent.com/madworx/cd-ci-glue/master/src/cd-ci-glue.bash)
   - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
   - sudo service docker restart

install:
  - docker build -t madworx/remoteswinglibrary:latest --squash .

script:
  - make test

after_success:
  - is_travis_master_push &&
    dockerhub_push_image madworx/remoteswinglibrary:latest &&
    dockerhub_push_image madworx/remoteswinglibrary:slim   &&
    dockerhub_set_description madworx/remoteswinglibrary README.md
